version: '3.8'
services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3303:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "secret2secret"
      MYSQL_DATABASE: "clean_arc"
      MYSQL_USER: "tester"
      MYSQL_PASSWORD: "secret2secret"
    networks:
      - default
    volumes:
      - mysql_data_clean:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

networks:
  default:
    name: cleanarc
volumes:
  mysql_data_clean:
